#!/bin/bash
# part of insulaudit-ssh-tools

echo $0
config=${1}

function do_socat ( ) {
  vmodem=${VMODEM-$WORK_BASE/vmodem}
  port=$(git config -f $WORK_CONF/audit.config --get serialtonet.port)
  baud=$(git config -f $WORK_CONF/audit.config --get serialtonet.baud || echo 9600)
  echo socat TCP-L:$port,reuseaddr pty,link=$vmodem,b${baud},raw
  exec  socat -d -d \
        pty,link=$vmodem,b${baud},waitslave,raw \
        TCP:localhost:$port 
}

( do_socat || echo "SOCAT DIED" ) &

#####
# EOF
