#!/bin/bash
# part of insulaudit-ssh-tools

echo $0
config=${1}

function do_socat ( ) {
  vmodem=${VMODEM-$WORK_BASE/vmodem}
  port=$(git config -f $WORK_CONF/audit.config --get serialtonet.port)
  baud=$(git config -f $WORK_CONF/audit.config --get serialtonet.baud || echo 9600)
  ADDR1="pty,link=$vmodem,waitslave,raw,b${baud}"
  ADDR2="TCP:localhost:$port"
  do_socat="-d -d $ADDR1 $ADDR2"
  echo socat $do_socat
  exec socat ${do_socat}
}

( do_socat || echo "SOCAT DIED" ) &

#####
# EOF
