#!/bin/bash
# part of insulaudit-ssh-tools
. common

echo $0

echo SHOULD I USE VMODEM: $VMODEM? $( test -f $VMODEM )
if [[ -a $VMODEM ]] ; then
  #echo "SNIFF FIRMWARE AND VERSION"
  (
  #echo insulaudit onetouch --port $VMODEM hello
  #insulaudit onetouch --port $VMODEM hello 
  echo insulaudit onetouch --port $VMODEM sugars
  insulaudit onetouch --port $VMODEM sugars
  ) 2>&1 | tee $WORK_LOCAL/incoming.log
else
  echo $VMODEM does not exist
fi

#####
# EOF
