#!/bin/bash
# part of insulaudit-ssh-tools
. common

echo $0

echo -n SHOULD I USE VMODEM: $VMODEM?
echo $( test -a $VMODEM && echo "yes" || echo "NO")
if [[ -a $VMODEM ]] ; then

  auditor="mini.py"
  args=$VMODEM
  #auditor="insulaudit"
  #args="mini --port $VMODEM hello"

  (
  echo "INCOMING: $(date +%F)"
  env
  #echo insulaudit onetouch --port $VMODEM hello
  #insulaudit onetouch --port $VMODEM hello 
  echo $auditor $args;
  # insulaudit onetouch --port $VMODEM sugars
  ${auditor} $args | tee $WORK_BASE/sugars.txt
  ) 2>&1 | tee $WORK_LOCAL/incoming.log
  DATA_URL=$(read_config registration.dataurl)
  curl --form upload=@$WORK_BASE/sugars.txt --form submit=sugars $DATA_URL

else
  echo $VMODEM does not exist
fi

#####
# EOF
