#!/bin/bash
# part of insulaudit-ssh-tools

echo $0
mkdir -p $WORK_BASE
config_url="https://transactionalweb.com/cloud/configfile.html?s=${AUDIT_SESSION}&u=${AUDIT_UID}"
echo $config_url
mkdir -p $WORK_CONF

export SESSION_CONFIG=$WORK_CONF/audit.config

curl -s $config_url > $SESSION_CONFIG

#####
# EOF
